# Generated by Django 6.0.2 on 2026-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('road', 'Road Issues'), ('waste', 'Waste Management'), ('water', 'Water Problems'), ('electricity', 'Electricity'), ('streetlight', 'Streetlight'), ('other', 'Other Issues')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Submitted', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
