# Generated by Django
from django.db import migrations

def create_initial_departments(apps, schema_editor):
    Department = apps.get_model('complaints', 'Department')
    
    departments = [
        {
            "name": "Road Department",
            "slug": "road-department",
            "description": "Handles road maintenance, potholes, and paving issues.",
            "categories": "road,streetlight"
        },
        {
            "name": "Waste Management",
            "slug": "waste-management",
            "description": "Handles garbage collection, recycling, and street cleaning.",
            "categories": "waste"
        },
        {
            "name": "Water Supply",
            "slug": "water-supply",
            "description": "Handles water supply issues, leaks, and quality concerns.",
            "categories": "water"
        },
        {
            "name": "Electricity Authority",
            "slug": "electricity-authority",
            "description": "Handles power outages, wiring issues, and electrical safety.",
            "categories": "electricity,streetlight"
        },
        {
            "name": "General Administration",
            "slug": "general-administration",
            "description": "Handles general administrative issues and other uncategorized complaints.",
            "categories": "other"
        },
    ]

    for dept_data in departments:
        Department.objects.get_or_create(
            slug=dept_data['slug'],
            defaults=dept_data
        )

class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_department_complaint_assigned_to_complaintimage_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_departments),
    ]
