# Generated by Django
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_initial_officers(apps, schema_editor):
    Department = apps.get_model('complaints', 'Department')
    AdminProfile = apps.get_model('complaints', 'AdminProfile')
    User = apps.get_model('auth', 'User')

    # Map department slug to desired admin user details
    officer_map = {
        'road-department': 'road_admin',
        'waste-management': 'waste_admin',
        'water-supply': 'water_admin',
        'electricity-authority': 'electricity_admin',
        'general-administration': 'general_admin',
    }

    for slug, username in officer_map.items():
        try:
            dept = Department.objects.get(slug=slug)
        except Department.DoesNotExist:
            continue

        # Create User
        user, created = User.objects.get_or_create(
            username=username,
            defaults={
                'email': f'{username}@example.com',
                'password': make_password('password123'),
                'is_staff': True,
                'first_name': dept.name.split(' ')[0],
                'last_name': 'Admin',
            }
        )

        # Create AdminProfile
        AdminProfile.objects.get_or_create(
            user=user,
            defaults={
                'department': dept,
                'role': 'department_head'
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_create_initial_departments'),
    ]

    operations = [
        migrations.RunPython(create_initial_officers),
    ]
